### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by masteryodaa** [k-m-irfan/Fastspeech2_HS_Flask_API#1]
It's giving me this error when installing the requirements:

Successfully built fast-bss-eval ctc-segmentation pyworld ci-sdr antlr4-python3-runtime jaconv lit distance
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects

**Comment by k-m-irfan** [comment]
apologies for the late response...
which OS are you using... windows or ubuntu? Also if you can share screenshot of the error

**Comment by k-m-irfan** [comment]
resolved
